spring.application.name=url-shortner-sb


#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/urlShortnerDB
spring.datasource.username=postgres
spring.datasource.password=6969
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret= jmg1GvazNGJf7HliSfaZU3r8Uur6Kkkb2CYNp2XHRDx
jwt.expiration= 600000

server.servlet.context-path=/api/v1